name: keystroke
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python
  - pip
  - pandas
  - cudatoolkit
  - pytorch
  - pip:
      - pynput
      - pytorch-lightning
      - wandb
      - tqdm
      - matplotlib
      - plotly

  